name: brain_microproteins
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  # Python environment
  - python>=3.10
  - pip
  
  # Python packages
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Bioinformatics tools
  - bedtools>=2.30.0
  - pybedtools>=0.9.0
  
  # R environment
  - r-base>=4.2.0
  - r-essentials
  
  # R packages for analysis
  - bioconductor-deseq2
  - r-dplyr
  - r-tibble
  - r-ggplot2
  - r-plotly
  - bioconductor-biomart
  - r-patchwork
  - r-ggpubr
  - bioconductor-org.hs.eg.db
  - bioconductor-annotationdbi
  
  # Additional Python packages via pip
  - pip:
    - plotly>=5.0.0
    - openpyxl>=3.0.0
